// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"wp2i6fgto8","name":"eb","description":"","endpoint":"https://wp2i6fgto8.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/ebtest","/ebtest/123"]}],
    'aws_cognito_identity_pool_id': 'us-east-1:6b99d246-ae47-42d1-8bfd-02036907260a',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'emberbee-hosting-mobilehub-300109055',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'dezo7f13qthyh.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-east-1',
    'aws_dynamodb_table_schemas': [{"tableName":"emberbee-mobilehub-300109055-task","attributes":[{"name":"userId","type":"S"},{"name":"category","type":"S"},{"name":"description","type":"S"}],"indexes":[],"region":"us-east-1","hashKey":"userId"}],
    'aws_mandatory_sign_in': 'enable',
    'aws_mobile_analytics_app_id': '9f1b732e50a64490b9f1cdc80a329982',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '8e32ca72-64df-4285-9732-b3a5345704f6',
    'aws_project_name': 'emberbee',
    'aws_project_region': 'us-east-1',
    'aws_resource_bucket_name': 'emberbee-deployments-mobilehub-300109055',
    'aws_resource_name_prefix': 'emberbee-mobilehub-300109055',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_jtB2n4vcz',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': '1kda4lodhpo6q6o4t2ppce23k4',
}

export default awsmobile;
