// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"p1lss4fuaa","name":"tasksnotesCRUD","description":"","endpoint":"https://p1lss4fuaa.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/tasksnotes","/tasksnotes/123"]}],
    'aws_cognito_identity_pool_id': 'us-east-1:43fce82f-e490-45ee-90c5-eb620db94d58',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'eb-hosting-mobilehub-1028859205',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd30zfd1hqet4ci.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-east-1',
    'aws_dynamodb_table_schemas': [{"tableName":"eb-mobilehub-1028859205-tasksnotes","attributes":[{"name":"userId","type":"S"},{"name":"notes","type":"L"},{"name":"settings","type":"M"},{"name":"tasks","type":"L"}],"indexes":[],"region":"us-east-1","hashKey":"userId"}],
    'aws_mobile_analytics_app_id': '1427531a45ce40c580ad4a4596b11ea6',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '1628d8d5-a41f-437c-a7a9-5f645d35b99b',
    'aws_project_name': 'eb-2018-04-28-01-03-26',
    'aws_project_region': 'us-east-1',
    'aws_resource_bucket_name': 'eb-deployments-mobilehub-1028859205',
    'aws_resource_name_prefix': 'eb-mobilehub-1028859205',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'eb-userfiles-mobilehub-1028859205',
    'aws_user_files_s3_bucket_region': 'us-east-1',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_baQAV2H0o',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': 'f5fr8ocnm53uda7rj5ih0pqrr',
}

export default awsmobile;
