// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-west-2:d2b6a7db-76f3-4e92-86f0-6d80e595c743',
    'aws_cognito_region': 'us-west-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'eb-hosting-mobilehub-1482378772',
    'aws_content_delivery_bucket_region': 'us-west-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd3cmviehmljewh.cloudfront.net',
    'aws_mobile_analytics_app_id': '8f258ec865a54894802e66ab25ba07ca',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '773c01b0-580e-4af4-8707-54e833134f9c',
    'aws_project_name': 'eb-2018-04-08-15-56-24',
    'aws_project_region': 'us-west-1',
    'aws_resource_name_prefix': 'eb-mobilehub-1482378772',
}

export default awsmobile;
